CREATE TABLE IF NOT EXISTS foods (
  id TEXT PRIMARY KEY,
  shop TEXT NOT NULL,
  place TEXT NOT NULL DEFAULT '',
  dishes TEXT NOT NULL DEFAULT '',
  rating INTEGER NOT NULL DEFAULT 5,
  note TEXT NOT NULL DEFAULT '',
  created_at TEXT NOT NULL
);
